"""Add trial period fields to User model

Revision ID: 8b7ef23eadb4
Revises: 
Create Date: 2026-03-26 10:45:02.667339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7ef23eadb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('has_trial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_trial')
        batch_op.drop_column('trial_end')
        batch_op.drop_column('trial_start')

    # ### end Alembic commands ###
