"""add profile_photo to User

Revision ID: 523583383b55
Revises: 55ef132dc42f
Create Date: 2026-04-02 18:10:14.391797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523583383b55'
down_revision = '55ef132dc42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('replies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')

    op.create_table('replies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('photo_filename', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
